CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  what TEXT NOT NULL,
  how TEXT,
  who TEXT,
  link TEXT,
  thoughts TEXT,
  favorite BOOLEAN,
  author INTEGER REFERENCES users(id) NOT NULL,
  date_created DATE DEFAULT now() NOT NULL,
  date_edited DATE DEFAULT now() NOT NULL,
  folder INTEGER REFERENCES folders(id) NOT NULL
);